apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi